# Generated by Django 6.0 on 2025-12-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, default='+7', max_length=5, verbose_name='Код страны телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL фото профиля'),
        ),
    ]
