# Generated by Django 5.2.9 on 2025-12-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_db', '0002_user_date_of_birth_user_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], max_length=20, verbose_name='Пол'),
        ),
    ]
