# Generated by Django 5.2.9 on 2025-12-17 03:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'faqs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
                'db_table': 'information_pages',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('us_canada', 'США и Канада'), ('europe', 'Европа'), ('asia', 'Азия и Австралия'), ('south_america', 'Южная Америка'), ('middle_east', 'Ближний Восток')], db_index=True, max_length=20, unique=True, verbose_name='Код региона')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('database_name', models.CharField(max_length=50, verbose_name='Имя БД')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
                'db_table': 'service_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=255, verbose_name='Администратор')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID объекта')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Лог действий администратора',
                'verbose_name_plural': 'Логи действий администраторов',
                'db_table': 'admin_action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='admin_actio_admin_u_81130f_idx'), models.Index(fields=['model_name', 'created_at'], name='admin_actio_model_n_0b1f1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='articles_is_publ_b5c0bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='IATA код')),
                ('icao_code', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True, verbose_name='ICAO код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='Страна')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_db.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
                'db_table': 'airports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название терминала')),
                ('code', models.CharField(max_length=10, verbose_name='Код терминала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='global_db.airport', verbose_name='Аэропорт')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
                'db_table': 'terminals',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='global_db.airport', verbose_name='Аэропорт')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_db.servicetype', verbose_name='Тип услуги')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='global_db.terminal', verbose_name='Терминал')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='UserRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_db.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Пользователь (реестр)',
                'verbose_name_plural': 'Реестр пользователей',
                'db_table': 'user_registry',
            },
        ),
        migrations.CreateModel(
            name='GlobalReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_email', models.EmailField(db_index=True, max_length=255, verbose_name='Email пригласившего')),
                ('referred_email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email приглашенного')),
                ('referral_code', models.CharField(db_index=True, max_length=20, verbose_name='Реферальный код')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_received', to='global_db.region', verbose_name='Регион приглашенного')),
                ('referrer_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to='global_db.region', verbose_name='Регион пригласившего')),
            ],
            options={
                'verbose_name': 'Глобальная реферальная связь',
                'verbose_name_plural': 'Глобальная реферальная система',
                'db_table': 'global_referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer_email', 'created_at'], name='global_refe_referre_99577c_idx'), models.Index(fields=['referred_email'], name='global_refe_referre_ee09fa_idx'), models.Index(fields=['referral_code'], name='global_refe_referra_1189d3_idx'), models.Index(fields=['referrer_region', 'referred_region'], name='global_refe_referre_7e57da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['region', 'is_active'], name='airports_region__2f49a4_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country', 'city'], name='airports_country_088041_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['airport', 'is_active'], name='terminals_airport_3fab07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('airport', 'code')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['airport', 'is_active'], name='services_airport_2b4dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='services_service_393478_idx'),
        ),
        migrations.AddIndex(
            model_name='userregistry',
            index=models.Index(fields=['email', 'is_active'], name='user_regist_email_d03dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='userregistry',
            index=models.Index(fields=['region', 'is_active'], name='user_regist_region__20e0f4_idx'),
        ),
    ]
